### ISSUE TITLE
[Question] How to quit opened apps?

### ISSUE THREAD

**Issue by sbruchmann** [sindresorhus/opn#2]
Hi @sindresorhus,

it seems like there’s currently no way to quit opened apps, since `opn` doesn’t return anything and the `callback` function gets executed once the corresponding app was terminated. Am I missing something?

**Comment by watson** [comment]
I've been toying with the same issue. How about allowing the user to provide a options hash with `{ wait: false }` to override the default behaviour of waiting if `opn` is called with a callback?

In that case it should just call the callback once the child processes returns from opening the URL.

**Comment by sindresorhus** [comment]
@watson :+1: Sounds like a better behaviour than the current way :)

**Comment by watson** [comment]
@sindresorhus Currently the api for the `opn` function is: `opn(target, [app], [callback])`. I think it would be to complicated to both understand and implement if we added an options hash between the `app` and the `callback` argument.

But since the `app` argument is seldom used, couldn't we then just make that part of the options hash? I.e. `opn(target, [options], [callback])`, where options have the following optional properties:

```js
{
  app: "..." // default is platform dependent
  wait: false // default is true
}
```

**Comment by watson** [comment]
That would of cause be a breaking change, which I would rather not introduce... but we could of cause detect if it was given a string and fall back to the old behaviour - or just bump the major version? Let me know what you think

**Comment by sindresorhus** [comment]
`opn(target, [options], [callback])` looks good to me.

I'm fine with breaking backwards compat in a major as I doubt the `app` feature is used much.

**Comment by watson** [comment]
@sindresorhus ^ here you go - let me know what you think :)
