### ISSUE TITLE
Unhandled promise rejection in Docker

### ISSUE THREAD

**Issue by imkimchi** [sindresorhus/opn#37]
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3

I apparently get this error when I open links using the module in Docker container. I tested the code in my local before I put the code on my server which uses Docker. And It literally works well in my local that doesn't use Docker. So I assume that something is wrong with docker but there's actually no way to figure out what the problem is. Is there anyone who has ever used 'opn' module with Docker?

Additionally, after I set node version of my server to the same as my local one, It doesn't says the promise error but still doesn't open any links.

**Comment by SamVerschueren** [comment]
Just wondering why you would use this inside a container... What's the use case?

**Comment by imkimchi** [comment]
@SamVerschueren  Oh dude.. I just realized `opn` is only for local machine.

I was making a website that compress multiple links to one link. so I tried to do it on client-side but the browser popup blocker prevents to open multiple links. so I tried to use this module to avoid the blocker and I could actually avoid it but I didn't realize that `opn` module is only for local machine. I wish I could exploit the browsers engine 😅

**Comment by ngelinas-mentel** [comment]
For those who develop with Docker on their local machines, you can get around this issue by only opening links conditionally.  In my situation, this was used by webpack to automatically open the browser on build.  I had to disable that in order to prevent this error.

@SamVerschueren , I'd recommend none the less catching such errors in a rejection handler as it can be quite common to work on teams that both use and don't use docker for development.  In this case, different environment settings are required while I think it'd be good to instead handle the case when opn fails to open the browser in this way.  Perhaps a `try {} catch` around the `childProcess.spawn` with `return Promise.reject(err)`?
