### ISSUE TITLE
how to open chrome page in new window every time

### ISSUE THREAD

**Issue by exolution** [sindresorhus/opn#39]
if exists a chrome instance , opn will open a tag on this chrome instance
i want to open a new instance

**Comment by sindresorhus** [comment]
Then you have to pass a flag to Chrome to tell it to do that. I don't remember which flag. Google it.

**Comment by dwieeb** [comment]
@sindresorhus The original issue probably could've provided more details.

I am seeing this with macOS with `open`:

```
open -a "google chrome" --args --new-window "https://google.com"
```

vs

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --new-window "https://google.com"
```

(run both commands twice to see that `open` does not open a new instance, but running chrome directly does)

The issue is the `-n` flag is not being passed to `open` to actually open a new instance of the application, and there [doesn't appear to be a way to pass flags to `open`](https://github.com/sindresorhus/opn/blob/master/index.js#L24-L32).

I'm not sure about the status of windows/linux.
